name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_launcher_icons: "0.14.4"

flutter:
  uses-material-design: true 
  assets:
    - assets/icon.png
    - assets/splashimage.png



flutter_launcher_icons: 
  android: true 
  ios: true
  image_path: 'assets/icon.png'



   